/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("exercises").del();
  await knex("exercises").insert([
    {
      id: 1,
      user_id: 1,
      created_at: new Date(1648290791000),
      rating_before: 5,
      location: "home",
      see_1: "couch",
      see_2: "water bottle",
      see_3: "lamp",
      see_4: "cat",
      see_5: "fridge",
      touch_1: "arm",
      touch_2: "phone",
      touch_3: "table",
      touch_4: "t-shirt",
      hear_1: "TV",
      hear_2: "rain",
      hear_3: "sneeze",
      smell_1: "pizza",
      smell_2: "candle",
      taste_1: "mint",
      rating_after: 2,
    },
    {
      id: 2,
      user_id: 1,
      created_at: new Date(1648290791000),
      rating_before: 4,
      location: "mall",
      see_1: "store",
      see_2: "bench",
      see_3: "shopper",
      see_4: "clothes",
      see_5: "palm tree",
      touch_1: "pocket",
      touch_2: "phone",
      touch_3: "purse",
      touch_4: "palm",
      hear_1: "chatter",
      hear_2: "music",
      hear_3: "footsteps",
      smell_1: "cinnamon buns",
      smell_2: "cleaner",
      taste_1: "strawberry lip balm",
      rating_after: 1,
    },
    {
      id: 3,
      user_id: 2,
      created_at: new Date(1648290791000),
      rating_before: 4,
      location: "work",
      see_1: "computer",
      see_2: "mouse",
      see_3: "picture",
      see_4: "pen",
      see_5: "mug",
      touch_1: "keyboard",
      touch_2: "sweater",
      touch_3: "pencil",
      touch_4: "notebook",
      hear_1: "chatter",
      hear_2: "footsteps",
      hear_3: "coffee machine",
      smell_1: "coffee",
      smell_2: "paper",
      taste_1: "coffee",
      rating_after: 1,
    },
    {
      id: 4,
      user_id: 1,
      created_at: new Date(1648290791000),
      rating_before: 3,
      location: "park",
      see_1: "trees",
      see_2: "grass",
      see_3: "flowers",
      see_4: "birds",
      see_5: "bench",
      touch_1: "leaves",
      touch_2: "ground",
      touch_3: "flower petals",
      touch_4: "feather",
      hear_1: "wind",
      hear_2: "birds chirping",
      hear_3: "kids playing",
      smell_1: "fresh air",
      smell_2: "flowers",
      taste_1: "picnic food",
      rating_after: 2,
    },
    {
      id: 5,
      user_id: 1,
      created_at: new Date(1648290791000),
      rating_before: 2,
      location: "beach",
      see_1: "sand",
      see_2: "waves",
      see_3: "seagulls",
      see_4: "beach umbrella",
      see_5: "ocean",
      touch_1: "sand",
      touch_2: "water",
      touch_3: "seashells",
      touch_4: "beach ball",
      hear_1: "waves crashing",
      hear_2: "seagulls calling",
      hear_3: "laughter",
      smell_1: "saltwater",
      smell_2: "sunscreen",
      taste_1: "ice cream",
      rating_after: 3,
    },
    {
      id: 6,
      user_id: 1,
      created_at: new Date(1648290791000),
      rating_before: 4,
      location: "movie theater",
      see_1: "screen",
      see_2: "seats",
      see_3: "popcorn",
      see_4: "people",
      see_5: "aisle",
      touch_1: "armrest",
      touch_2: "popcorn bucket",
      touch_3: "drink cup",
      touch_4: "ticket",
      hear_1: "movie soundtrack",
      hear_2: "people chatting",
      hear_3: "rustling",
      smell_1: "popcorn",
      smell_2: "butter",
      taste_1: "soda",
      rating_after: 5,
    },
    {
      id: 7,
      user_id: 1,
      created_at: new Date(1648290791000),
      rating_before: 5,
      location: "restaurant",
      see_1: "tables",
      see_2: "chairs",
      see_3: "menu",
      see_4: "waiter",
      see_5: "decor",
      touch_1: "tablecloth",
      touch_2: "menu",
      touch_3: "glass",
      touch_4: "fork",
      hear_1: "conversations",
      hear_2: "clinking of glasses",
      hear_3: "sizzle of food",
      smell_1: "food aroma",
      smell_2: "herbs",
      taste_1: "appetizer",
      rating_after: 4,
    },
  ]);
};
